### Create a new product
POST http://localhost:3000/products
content-type: application/json

{
	"name": "Product 4",
	"detail": "Product 4 detail",
	"price": 100,
	"quantity": 10
}

### Get all products
GET http://localhost:3000/products
content-type: application/json
###

### Get by id
GET http://localhost:3000/products/65ffbc35f6ea5ef91ab97444
content-type: application/json
###

### Put by id
PUT http://localhost:3000/products/65ffbc35f6ea5ef91ab97444
content-type: application/json

{
	"name": "Product 4",
	"detail": "Product 4 detail update",
	"price": 99,
	"quantity": 999
}
###

### Patch by id
PATCH http://localhost:3000/products/65ffbc35f6ea5ef91ab97444
content-type: application/json

{
	"price": 102,
	"quantity": 1001
}
###

### Delete by id
DELETE http://localhost:3000/products/65ffbc35f6ea5ef91ab97444
content-type: application/json
###
